/// Process management — process table, IPC, context switching, scheduling, lifecycle.
///
/// Phase 12: Preemptive Scheduling (timer-driven context switches).
///
/// Design:
///   - Fixed-size process table (no dynamic allocation in kernel)
///   - Synchronous send/receive: sender blocks until receiver picks up
///   - Call/Reply: RPC in one ecall (send + wait for reply)
///   - Context switch via TrapFrame save/restore on the kernel stack
///   - Each process has its own Sv39 page table
///
/// IPC model:
///   SYS_SEND(target, msg)   — blocks until target calls RECEIVE
///   SYS_RECEIVE(from)       — blocks until someone sends to us
///   SYS_CALL(target, msg)   — send + block for SYS_REPLY (RPC)
///   SYS_REPLY(target, reply)— deliver reply to BlockedCall process (non-blocking)
///   Rendezvous: when send and receive meet, message transfers, both unblock.
///   This is the seL4 model — no kernel-side message queues, no allocation.

use core::arch::{asm, global_asm};
use crate::page_alloc::PAGE_SIZE;
use crate::page_table::*;
use crate::trap::TrapFrame;
use crate::kvm;
use crate::println;

// ── Constants ──────────────────────────────────────────────────

const MAX_PROCS: usize = 8;

// ── Process State Machine ──────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ProcessState {
    Free,           // Slot is unused
    Ready,          // Can be scheduled
    Running,        // Currently executing
    BlockedSend,    // Waiting for receiver to call RECEIVE
    BlockedRecv,    // Waiting for sender to call SEND
    BlockedCall,    // Sent via SYS_CALL, waiting for SYS_REPLY
    BlockedWait,    // Waiting for child process to exit (SYS_WAIT)
}

// ── Process Control Block ──────────────────────────────────────

#[derive(Clone, Copy)]
pub struct Process {
    pub pid: usize,
    pub state: ProcessState,
    pub satp: u64,
    pub context: TrapFrame,     // Saved registers (for context switch)
    // IPC state
    pub ipc_target: usize,      // Who we're sending to / expecting from (0 = any)
    pub ipc_value: usize,       // Message being sent
    // Lifecycle
    pub parent: usize,          // Parent PID (0 = kernel-spawned)
    pub exit_code: usize,       // Stored when process exits
}

impl Process {
    const fn empty() -> Self {
        Process {
            pid: 0,
            state: ProcessState::Free,
            satp: 0,
            context: TrapFrame::zero(),
            ipc_target: 0,
            ipc_value: 0,
            parent: 0,
            exit_code: 0,
        }
    }
}

// ── Process Table (kernel global state) ────────────────────────

/// Process table — fixed size, no heap allocation.
/// PID 0 is reserved (kernel). Processes use PIDs 1..MAX_PROCS-1.
static mut PROCS: [Process; MAX_PROCS] = [Process::empty(); MAX_PROCS];

/// PID of the currently running process.
static mut CURRENT_PID: usize = 0;

// ── ELF Binaries (generated by gen_elf.py) ────────────────────

/// Spinner: busy-loop 1M iterations, then SYS_EXIT(99).
/// The adversary — hogs the CPU, never calls a syscall during the loop.
/// Without preemption, this starves every other process.
/// 148 bytes, entry=0x10078.
const SPINNER_ELF: [u8; 148] = [
    0x7F, 0x45, 0x4C, 0x46, 0x02, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x02, 0x00, 0xF3, 0x00, 0x01, 0x00, 0x00, 0x00, 0x78, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x38, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x94, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x94, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x93, 0x02, 0x00, 0x00, 0x37, 0x03, 0x10, 0x00,
    0x93, 0x82, 0x12, 0x00, 0xE3, 0x9C, 0x62, 0xFE, 0x93, 0x08, 0x10, 0x00, 0x13, 0x05, 0x30, 0x06,
    0x73, 0x00, 0x00, 0x00,
];

/// Goose counter: GETPID → derive char → busy-delay → print × 50 → exit.
/// Each goose spins 1M iterations in U-mode between PUTCHAR calls,
/// giving the timer interrupt a window to preempt. This produces the
/// visible interleaving that proves preemptive scheduling works.
/// PID 2→'A', PID 3→'B', PID 4→'C'.
/// 200 bytes, entry=0x10078.
const GOOSE_ELF: [u8; 200] = [
    0x7F, 0x45, 0x4C, 0x46, 0x02, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x02, 0x00, 0xF3, 0x00, 0x01, 0x00, 0x00, 0x00, 0x78, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x38, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xC8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x93, 0x08, 0xC0, 0x00, 0x73, 0x00, 0x00, 0x00,
    0x13, 0x04, 0xF5, 0x03, 0x93, 0x04, 0x20, 0x03, 0x63, 0x84, 0x04, 0x02, 0xB7, 0x02, 0x10, 0x00,
    0x93, 0x82, 0x02, 0x00, 0x93, 0x82, 0xF2, 0xFF, 0xE3, 0x9E, 0x02, 0xFE, 0x93, 0x08, 0x00, 0x00,
    0x13, 0x05, 0x04, 0x00, 0x73, 0x00, 0x00, 0x00, 0x93, 0x84, 0xF4, 0xFF, 0x6F, 0xF0, 0xDF, 0xFD,
    0x93, 0x08, 0x00, 0x00, 0x13, 0x05, 0xA0, 0x00, 0x73, 0x00, 0x00, 0x00, 0x93, 0x08, 0x10, 0x00,
    0x13, 0x05, 0x00, 0x00, 0x73, 0x00, 0x00, 0x00,
];

// ── Embedded User Programs ─────────────────────────────────────

// Program 1: init (PID 1) — Dining Geese orchestrator
// Phase 12: Spawns a spinner (hog) + 3 goose counters from ELF binaries.
// The spinner busy-loops (no syscalls) — preemption is the ONLY way the
// geese get to run. Init waits for all children, then exits.
// Demonstrates: SYS_SPAWN × 4, SYS_WAIT × 4, preemptive scheduling.
global_asm!(r#"
.section .text
.balign 4
.global _user_init_start
.global _user_init_end

_user_init_start:
    # ─── GooseOS init process (PID 1) ───
    # Phase 12: Dining Geese — preemptive scheduling demo.
    #
    # Spawns 3 goose counters FIRST (so they get PIDs 2,3,4),
    # then the spinner hog LAST (PID 5). This avoids PID-slot
    # reuse if the spinner exits before all spawns complete.
    #
    # Registers:
    #   s0 = goose ELF address (0x5F001000)
    #   s1 = goose ELF size (200 bytes)
    #   s2 = spinner ELF address (0x5F000000)
    #   s3 = spinner ELF size (148 bytes)
    #   s4 = goose A PID
    #   s5 = goose B PID
    #   s6 = goose C PID
    #   s7 = spinner PID

    li      s0, 0x5F001000      # goose ELF
    li      s1, 200             # goose size
    li      s2, 0x5F000000      # spinner ELF
    li      s3, 148             # spinner size

    # ── Spawn goose A ──
    li      a7, 10              # SYS_SPAWN
    mv      a0, s0
    mv      a1, s1
    ecall
    li      t0, -1
    beq     a0, t0, .fail
    mv      s4, a0              # save goose A PID

    # ── Spawn goose B ──
    li      a7, 10              # SYS_SPAWN
    mv      a0, s0
    mv      a1, s1
    ecall
    li      t0, -1
    beq     a0, t0, .fail
    mv      s5, a0              # save goose B PID

    # ── Spawn goose C ──
    li      a7, 10              # SYS_SPAWN
    mv      a0, s0
    mv      a1, s1
    ecall
    li      t0, -1
    beq     a0, t0, .fail
    mv      s6, a0              # save goose C PID

    # ── Spawn spinner (hog) — last, so it gets the highest PID ──
    li      a7, 10              # SYS_SPAWN
    mv      a0, s2
    mv      a1, s3
    ecall
    li      t0, -1
    beq     a0, t0, .fail
    mv      s7, a0              # save spinner PID

    # ── Wait for all geese ──
    li      a7, 11              # SYS_WAIT
    mv      a0, s4              # goose A
    ecall
    li      a7, 11              # SYS_WAIT
    mv      a0, s5              # goose B
    ecall
    li      a7, 11              # SYS_WAIT
    mv      a0, s6              # goose C
    ecall

    # ── Wait for spinner ──
    li      a7, 11              # SYS_WAIT
    mv      a0, s7              # spinner
    ecall

    # ── Exit success ──
    li      a7, 1               # SYS_EXIT
    li      a0, 0               # code 0
    ecall

1:  j       1b

.fail:
    # Spawn failed
    li      a7, 1               # SYS_EXIT
    li      a0, 1               # code 1 (failure)
    ecall

2:  j       2b

_user_init_end:
"#);

// No PID 2 server needed for Phase 12 — all processes are ELF-spawned by init.

// ── Boot: Create Processes and Launch ──────────────────────────

/// Create init process and launch it.
///
/// Phase 12: Only init (PID 1) is kernel-created. All other processes
/// are spawned at runtime by init from ELF binaries.
pub fn launch() -> ! {
    extern "C" {
        static _user_init_start: u8;
        static _user_init_end: u8;
    }

    let init_start = unsafe { &_user_init_start as *const u8 as usize };
    let init_size = unsafe { &_user_init_end as *const u8 as usize } - init_start;

    println!("  [proc] Creating init...");

    create_process(1, init_start, init_size);

    // Map ELF binaries into PID 1's address space ("initfs").
    // Spinner at VA 0x5F000000, Goose at VA 0x5F001000.
    let root1 = kvm::satp_to_root(unsafe { PROCS[1].satp });

    let spinner_page = kvm::alloc_zeroed_page();
    unsafe {
        let src = SPINNER_ELF.as_ptr();
        let dst = spinner_page as *mut u8;
        for i in 0..SPINNER_ELF.len() {
            core::ptr::write_volatile(dst.add(i), core::ptr::read_volatile(src.add(i)));
        }
    }
    kvm::map_user_page(root1, 0x5F00_0000, spinner_page, USER_RW);
    println!("  [proc] Mapped spinner ELF ({} bytes) at VA {:#x}",
        SPINNER_ELF.len(), 0x5F00_0000usize);

    let goose_page = kvm::alloc_zeroed_page();
    unsafe {
        let src = GOOSE_ELF.as_ptr();
        let dst = goose_page as *mut u8;
        for i in 0..GOOSE_ELF.len() {
            core::ptr::write_volatile(dst.add(i), core::ptr::read_volatile(src.add(i)));
        }
    }
    kvm::map_user_page(root1, 0x5F00_1000, goose_page, USER_RW);
    println!("  [proc] Mapped goose ELF ({} bytes) at VA {:#x}",
        GOOSE_ELF.len(), 0x5F00_1000usize);

    let alloc = unsafe { crate::page_alloc::get() };
    println!();
    println!("  [page_alloc] {} pages used, {} free",
        alloc.allocated_count(), alloc.free_count());
    println!();

    // Launch PID 1 as the first running process
    let proc1 = unsafe { &PROCS[1] };
    unsafe {
        CURRENT_PID = 1;
        PROCS[1].state = ProcessState::Running;
    }

    let entry = proc1.context.sepc;
    let user_sp = proc1.context.sp;
    let satp = proc1.satp;

    println!("  [proc] Launching PID 1 (init)...");
    println!();

    unsafe {
        asm!(
            "csrw sepc, {entry}",
            "csrr t0, sstatus",
            "li t1, -257",              // clear SPP (bit 8)
            "and t0, t0, t1",
            "ori t0, t0, 32",           // set SPIE (bit 5)
            "csrw sstatus, t0",
            "csrw sscratch, sp",        // save kernel sp
            "csrw satp, {satp}",
            "sfence.vma zero, zero",
            "mv sp, {user_sp}",
            "sret",
            entry = in(reg) entry,
            satp = in(reg) satp,
            user_sp = in(reg) user_sp,
            options(noreturn),
        );
    }
}

// ── Syscall Handlers ───────────────────────────────────────────

/// SYS_CALL(target_pid, msg_value) — synchronous RPC (send + wait for reply).
///
/// Convention: a0 = target PID, a1 = message value.
/// Returns:    a0 = reply value (set by SYS_REPLY from server).
///
/// The caller sends a message and blocks until the target calls SYS_REPLY.
/// This halves the syscall cost of an RPC round-trip compared to
/// separate SYS_SEND + SYS_RECEIVE — one ecall instead of two.
///
/// Behavior:
///   - If target is BlockedRecv: rendezvous (deliver msg), but caller
///     stays BlockedCall until the target does SYS_REPLY.
///   - If target is NOT BlockedRecv: caller blocks as BlockedCall,
///     msg waits until target calls SYS_RECEIVE.
pub fn sys_call(frame: &mut TrapFrame) {
    frame.sepc += 4; // advance past ecall (saved with context)

    let current = unsafe { CURRENT_PID };
    let target_pid = frame.a0;
    let msg_value = frame.a1;

    // Validate target
    if target_pid == 0 || target_pid >= MAX_PROCS || target_pid == current {
        frame.a0 = usize::MAX; // error
        return;
    }

    unsafe {
        let target_state = PROCS[target_pid].state;
        let target_wants = PROCS[target_pid].ipc_target;

        // Check if target is blocked on RECEIVE (from us or from any)
        if target_state == ProcessState::BlockedRecv
            && (target_wants == 0 || target_wants == current)
        {
            // Rendezvous! Deliver message to receiver's saved context.
            PROCS[target_pid].context.a0 = msg_value;  // message
            PROCS[target_pid].context.a1 = current;     // sender PID
            PROCS[target_pid].state = ProcessState::Ready;
        }

        // Caller ALWAYS blocks — even after rendezvous.
        // The difference from SYS_SEND: SYS_SEND unblocks on rendezvous,
        // SYS_CALL stays blocked waiting for SYS_REPLY.
        PROCS[current].ipc_target = target_pid;
        PROCS[current].ipc_value = msg_value;
        PROCS[current].state = ProcessState::BlockedCall;

        schedule(frame, current);
    }
}

/// SYS_REPLY(target_pid, reply_value) — deliver reply to a SYS_CALL caller.
///
/// Convention: a0 = caller PID, a1 = reply value.
/// Returns:    a0 = 0 (success), usize::MAX (error).
///
/// Non-blocking for the server — it continues running after replying.
/// The target must be in BlockedCall state and must have called US.
/// This prevents random processes from replying to calls they didn't receive.
pub fn sys_reply(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let current = unsafe { CURRENT_PID };
    let target_pid = frame.a0;
    let reply_value = frame.a1;

    // Validate target
    if target_pid == 0 || target_pid >= MAX_PROCS || target_pid == current {
        frame.a0 = usize::MAX;
        return;
    }

    unsafe {
        // Target must be BlockedCall AND must have called us
        if PROCS[target_pid].state == ProcessState::BlockedCall
            && PROCS[target_pid].ipc_target == current
        {
            // Deliver reply to caller's saved context
            PROCS[target_pid].context.a0 = reply_value;
            PROCS[target_pid].state = ProcessState::Ready;

            // Server continues — non-blocking
            frame.a0 = 0;
            return;
        }

        // No matching BlockedCall — error
        frame.a0 = usize::MAX;
    }
}

// ── Memory Management Syscalls ────────────────────────────────

/// SYS_MAP(phys, virt, flags) — map a physical page into caller's address space.
///
/// Convention: a0 = physical address, a1 = virtual address, a2 = flags.
///   flags: 0 = USER_RW, 1 = USER_RX
/// Returns: a0 = 0 (success), usize::MAX (error).
///
/// Validates:
///   - phys and virt are page-aligned
///   - virt is in user-mappable range (not kernel space)
///   - phys was allocated via SYS_ALLOC_PAGES
pub fn sys_map(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let phys = frame.a0;
    let virt = frame.a1;
    let flags_arg = frame.a2;

    // Validate alignment
    if phys % PAGE_SIZE != 0 || virt % PAGE_SIZE != 0 {
        frame.a0 = usize::MAX;
        return;
    }

    // Validate virt is in user range (below kernel space).
    // Reject addresses in kernel region and MMIO regions.
    // Simple check: user VA must be >= 0x5000_0000 and < 0x8000_0000
    // (avoids UART at 0x1000_0000, PLIC at 0x0C00_0000, kernel at 0x8020_0000+)
    if virt < 0x5000_0000 || virt >= 0x8000_0000 {
        frame.a0 = usize::MAX;
        return;
    }

    // Validate phys is an allocated page
    let alloc = unsafe { crate::page_alloc::get() };
    if !alloc.is_allocated(phys) {
        frame.a0 = usize::MAX;
        return;
    }

    // Map flags: 0 = USER_RW, 1 = USER_RX
    let pte_flags = match flags_arg {
        0 => crate::page_table::USER_RW,
        1 => crate::page_table::USER_RX,
        _ => {
            frame.a0 = usize::MAX;
            return;
        }
    };

    // Get current process's page table root
    let current = unsafe { CURRENT_PID };
    let satp = unsafe { PROCS[current].satp };
    let root = kvm::satp_to_root(satp);

    // Map the page
    kvm::map_user_page(root, virt, phys, pte_flags);

    // Flush TLB for this VA
    unsafe {
        core::arch::asm!("sfence.vma {}, zero", in(reg) virt);
    }

    frame.a0 = 0;
}

/// SYS_UNMAP(virt) — remove a page mapping from caller's address space.
///
/// Convention: a0 = virtual address.
/// Returns: a0 = 0 (success), usize::MAX (error).
///
/// Does NOT free the physical page — use SYS_FREE_PAGES for that.
pub fn sys_unmap(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let virt = frame.a0;

    if virt % PAGE_SIZE != 0 {
        frame.a0 = usize::MAX;
        return;
    }

    let current = unsafe { CURRENT_PID };
    let satp = unsafe { PROCS[current].satp };
    let root = kvm::satp_to_root(satp);

    if kvm::unmap_page(root, virt) {
        // Flush TLB for this VA
        unsafe {
            core::arch::asm!("sfence.vma {}, zero", in(reg) virt);
        }
        frame.a0 = 0;
    } else {
        frame.a0 = usize::MAX;
    }
}

/// SYS_ALLOC_PAGES(count) — allocate physical pages.
///
/// Convention: a0 = count (must be 1 for now).
/// Returns: a0 = physical address of allocated page, usize::MAX on error.
///
/// The page is zeroed before returning. Caller must SYS_MAP it
/// before accessing it — the page is not automatically mapped.
pub fn sys_alloc_pages(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let count = frame.a0;

    // Only single-page allocations for now
    if count != 1 {
        frame.a0 = usize::MAX;
        return;
    }

    let alloc = unsafe { crate::page_alloc::get() };
    match alloc.alloc() {
        Ok(phys) => {
            unsafe { crate::page_alloc::BitmapAllocator::zero_page(phys); }
            frame.a0 = phys;
        }
        Err(_) => {
            frame.a0 = usize::MAX;
        }
    }
}

/// SYS_FREE_PAGES(phys, count) — return physical pages to the kernel.
///
/// Convention: a0 = physical address, a1 = count (must be 1 for now).
/// Returns: a0 = 0 (success), usize::MAX (error).
///
/// The page is zeroed (security: don't leak data between processes).
/// Caller should SYS_UNMAP first if the page is still mapped.
pub fn sys_free_pages(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let phys = frame.a0;
    let count = frame.a1;

    if count != 1 {
        frame.a0 = usize::MAX;
        return;
    }

    // Zero the page before freeing (security)
    unsafe { crate::page_alloc::BitmapAllocator::zero_page(phys); }

    let alloc = unsafe { crate::page_alloc::get() };
    match alloc.free(phys) {
        Ok(()) => {
            frame.a0 = 0;
        }
        Err(_) => {
            frame.a0 = usize::MAX;
        }
    }
}

// ── Process Spawn ─────────────────────────────────────────────

/// SYS_SPAWN(elf_ptr, elf_len) — create a new process from an ELF binary.
///
/// Convention: a0 = pointer to ELF data (in caller's memory), a1 = length.
/// Returns: a0 = new PID, usize::MAX on error.
///
/// Parses the ELF, allocates pages for each LOAD segment, copies data,
/// builds a user page table, and registers the process as Ready.
pub fn sys_spawn(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let elf_ptr = frame.a0;
    let elf_len = frame.a1;
    let parent = unsafe { CURRENT_PID };

    // Basic validation
    if elf_len == 0 || elf_len > 1024 * 1024 {
        frame.a0 = usize::MAX;
        return;
    }

    // Enable Supervisor User Memory access (SUM bit in sstatus).
    // Without this, S-mode cannot read pages with the U bit set.
    // trap.S will restore the original sstatus before sret, so
    // this only affects the current trap handling.
    unsafe { asm!("csrs sstatus, {}", in(reg) 1usize << 18); }

    // Read the ELF data from caller's address space
    let elf_data = unsafe {
        core::slice::from_raw_parts(elf_ptr as *const u8, elf_len)
    };

    // Parse ELF headers
    let info = match crate::elf::parse(elf_data) {
        Ok(info) => info,
        Err(_) => {
            frame.a0 = usize::MAX;
            return;
        }
    };

    // Find a free process slot
    let mut new_pid = 0;
    unsafe {
        for i in 1..MAX_PROCS {
            if PROCS[i].state == ProcessState::Free {
                new_pid = i;
                break;
            }
        }
    }
    if new_pid == 0 {
        frame.a0 = usize::MAX;
        return;
    }

    // Build user page table
    let user_root = kvm::alloc_zeroed_page();
    kvm::map_kernel_regions(user_root);

    // Load each segment
    for seg_idx in 0..info.num_segments {
        let seg = &info.segments[seg_idx];
        let flags = if seg.executable { USER_RX } else { USER_RW };

        let num_pages = crate::elf::pages_needed(seg.memsz, seg.vaddr);
        let base_va = seg.vaddr & !(PAGE_SIZE - 1);

        for p in 0..num_pages {
            let va = base_va + p * PAGE_SIZE;
            let page = kvm::alloc_zeroed_page();

            // Calculate how much of this page needs file data
            let page_start = va;
            let page_end = va + PAGE_SIZE;

            let seg_file_start = seg.vaddr;
            let seg_file_end = seg.vaddr + seg.filesz;

            // Overlap between [page_start..page_end] and [seg_file_start..seg_file_end]
            let copy_start = if seg_file_start > page_start { seg_file_start } else { page_start };
            let copy_end = if seg_file_end < page_end { seg_file_end } else { page_end };

            if copy_start < copy_end {
                let file_offset = seg.file_offset + (copy_start - seg.vaddr);
                let dst_offset = copy_start - page_start;
                let len = copy_end - copy_start;

                unsafe {
                    let src = elf_data.as_ptr().add(file_offset);
                    let dst = (page as *mut u8).add(dst_offset);
                    for b in 0..len {
                        core::ptr::write_volatile(dst.add(b), core::ptr::read_volatile(src.add(b)));
                    }
                }
            }
            // memsz > filesz portion is already zeroed (alloc_zeroed_page)

            kvm::map_user_page(user_root, va, page, flags);
        }
    }

    // Allocate user stack (one page)
    let user_stack = kvm::alloc_zeroed_page();
    let stack_va = 0x7FFF_0000; // Fixed stack VA for spawned processes
    kvm::map_user_page(user_root, stack_va, user_stack, USER_RW);
    let user_sp = stack_va + PAGE_SIZE;

    let satp = make_satp(user_root, new_pid as u16);

    // Set up initial context
    let mut ctx = TrapFrame::zero();
    ctx.sepc = info.entry;
    ctx.sp = user_sp;
    ctx.sstatus = 1 << 5; // SPIE=1, SPP=0 (U-mode)

    unsafe {
        PROCS[new_pid] = Process {
            pid: new_pid,
            state: ProcessState::Ready,
            satp,
            context: ctx,
            ipc_target: 0,
            ipc_value: 0,
            parent,
            exit_code: 0,
        };
    }

    println!("  [kernel] PID {} spawned by PID {} (entry={:#x})",
        new_pid, parent, info.entry);

    frame.a0 = new_pid;
}

/// Kernel-level spawn for boot processes (not via syscall).
/// Used by launch() to create initial processes from embedded assembly.
fn create_process(
    pid: usize,
    code_start: usize,
    code_size: usize,
) {
    assert!(pid > 0 && pid < MAX_PROCS, "invalid PID");

    let user_code = kvm::alloc_zeroed_page();
    unsafe {
        let src = code_start as *const u8;
        let dst = user_code as *mut u8;
        for i in 0..code_size {
            core::ptr::write_volatile(dst.add(i), core::ptr::read_volatile(src.add(i)));
        }
    }

    let user_stack = kvm::alloc_zeroed_page();
    let user_sp = user_stack + PAGE_SIZE;

    let user_root = kvm::alloc_zeroed_page();
    kvm::map_kernel_regions(user_root);
    kvm::map_range(user_root, user_code, user_code + PAGE_SIZE, USER_RX);
    kvm::map_range(user_root, user_stack, user_stack + PAGE_SIZE, USER_RW);

    let satp = make_satp(user_root, pid as u16);

    let mut ctx = TrapFrame::zero();
    ctx.sepc = user_code;
    ctx.sp = user_sp;
    ctx.sstatus = 1 << 5;

    unsafe {
        PROCS[pid] = Process {
            pid,
            state: ProcessState::Ready,
            satp,
            context: ctx,
            ipc_target: 0,
            ipc_value: 0,
            parent: 0,
            exit_code: 0,
        };
    }

    println!("  [proc] PID {} created (code={:#x}, {} bytes, sp={:#x}, satp={:#018x})",
        pid, user_code, code_size, user_sp, satp);
}

// ── IPC Syscall Handlers ──────────────────────────────────────

/// SYS_SEND(target_pid, msg_value) — synchronous send.
///
/// Convention: a0 = target PID, a1 = message value.
/// Returns: a0 = 0 (success).
///
/// Blocks the sender until the target calls SYS_RECEIVE.
/// If the target is already blocked on RECEIVE, rendezvous immediately.
pub fn sys_send(frame: &mut TrapFrame) {
    frame.sepc += 4; // advance past ecall

    let current = unsafe { CURRENT_PID };
    let target_pid = frame.a0;
    let msg_value = frame.a1;

    // Validate target
    if target_pid == 0 || target_pid >= MAX_PROCS || target_pid == current {
        frame.a0 = usize::MAX; // error
        return;
    }

    unsafe {
        let target_state = PROCS[target_pid].state;
        let target_wants = PROCS[target_pid].ipc_target;

        // Check if target is blocked on RECEIVE (from us or from any)
        if target_state == ProcessState::BlockedRecv
            && (target_wants == 0 || target_wants == current)
        {
            // Rendezvous! Transfer message directly to receiver's saved context.
            PROCS[target_pid].context.a0 = msg_value;     // message
            PROCS[target_pid].context.a1 = current;        // sender PID
            PROCS[target_pid].state = ProcessState::Ready;

            // Sender continues — send returns success
            frame.a0 = 0;
            return;
        }

        // No rendezvous — block the sender
        PROCS[current].ipc_target = target_pid;
        PROCS[current].ipc_value = msg_value;
        PROCS[current].state = ProcessState::BlockedSend;

        // Context switch to the next ready process
        schedule(frame, current);
    }
}

/// SYS_RECEIVE(from_pid) — synchronous receive.
///
/// Convention: a0 = expected sender PID (0 = accept from anyone).
/// Returns: a0 = message value, a1 = sender PID.
///
/// Blocks the receiver until someone calls SYS_SEND targeting us.
/// If a sender is already blocked, rendezvous immediately.
pub fn sys_receive(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let current = unsafe { CURRENT_PID };
    let from_pid = frame.a0; // 0 = any

    unsafe {
        // Check if any sender is blocked waiting to send to us.
        // Match both BlockedSend (from SYS_SEND) and BlockedCall (from SYS_CALL).
        // The server's RECEIVE doesn't care how the sender sent — it gets the
        // message either way. The difference is what happens when the server
        // replies: BlockedSend processes were already unblocked, BlockedCall
        // processes stay blocked until SYS_REPLY delivers the response.
        for i in 1..MAX_PROCS {
            let is_sender = PROCS[i].state == ProcessState::BlockedSend
                || PROCS[i].state == ProcessState::BlockedCall;

            if is_sender
                && PROCS[i].ipc_target == current
                && (from_pid == 0 || from_pid == i)
            {
                // Rendezvous! Transfer message.
                let msg = PROCS[i].ipc_value;
                let sender = i;

                // Unblock sender ONLY if it was a plain SEND.
                // BlockedCall stays blocked — it's waiting for SYS_REPLY.
                if PROCS[i].state == ProcessState::BlockedSend {
                    PROCS[i].state = ProcessState::Ready;
                    PROCS[i].context.a0 = 0; // send returns 0
                }
                // BlockedCall: leave state as BlockedCall, target stays set.
                // SYS_REPLY will unblock it later.

                // Receiver gets the message
                frame.a0 = msg;
                frame.a1 = sender;
                return;
            }
        }

        // No sender found — block the receiver
        PROCS[current].ipc_target = from_pid;
        PROCS[current].state = ProcessState::BlockedRecv;

        // Context switch to the next ready process
        schedule(frame, current);
    }
}

/// SYS_EXIT(code) — terminate the current process.
///
/// Frees the process slot and switches to the next ready process.
/// If no processes remain, returns to kernel idle loop.
pub fn sys_exit(frame: &mut TrapFrame) {
    let current = unsafe { CURRENT_PID };
    let exit_code = frame.a0;

    println!();
    println!("  [kernel] PID {} exited with code {}", current, exit_code);

    unsafe {
        PROCS[current].state = ProcessState::Free;
        PROCS[current].exit_code = exit_code;

        // Wake any parent that's BlockedWait on us
        for i in 1..MAX_PROCS {
            if PROCS[i].state == ProcessState::BlockedWait
                && PROCS[i].ipc_target == current
            {
                // Deliver exit code to parent's saved context
                PROCS[i].context.a0 = exit_code;
                PROCS[i].state = ProcessState::Ready;
                break; // only one parent
            }
        }

        // Find next ready process
        let mut next = 0;
        for i in 1..MAX_PROCS {
            if PROCS[i].state == ProcessState::Ready {
                next = i;
                break;
            }
        }

        if next == 0 {
            // No runnable processes — return to kernel
            println!("  [kernel] All processes finished.");

            let kernel_satp = crate::kvm::kernel_satp();
            asm!(
                "csrw satp, {0}",
                "sfence.vma zero, zero",
                in(reg) kernel_satp,
            );

            // Rewrite frame to return to S-mode at post_process_exit
            frame.sstatus |= 1 << 8;  // SPP = S-mode
            frame.sstatus |= 1 << 5;  // SPIE = 1
            frame.sepc = crate::trap::post_process_exit as *const () as usize;
            return;
        }

        // Switch to next process
        *frame = PROCS[next].context;
        PROCS[next].state = ProcessState::Running;
        CURRENT_PID = next;

        let next_satp = PROCS[next].satp;
        asm!(
            "csrw satp, {0}",
            "sfence.vma zero, zero",
            in(reg) next_satp,
        );
    }
}

// ── Lifecycle Syscall Handlers ────────────────────────────────

/// SYS_GETPID() — return the current process's PID.
///
/// Convention: no arguments. Returns: a0 = PID.
pub fn sys_getpid(frame: &mut TrapFrame) {
    frame.sepc += 4;
    frame.a0 = unsafe { CURRENT_PID };
}

/// SYS_WAIT(child_pid) — block until a child process exits.
///
/// Convention: a0 = child PID.
/// Returns: a0 = child's exit code, usize::MAX on error.
///
/// If the child has already exited (Free state), returns immediately
/// with the stored exit code. Otherwise blocks until the child calls SYS_EXIT.
pub fn sys_wait(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let current = unsafe { CURRENT_PID };
    let child_pid = frame.a0;

    // Validate
    if child_pid == 0 || child_pid >= MAX_PROCS || child_pid == current {
        frame.a0 = usize::MAX;
        return;
    }

    unsafe {
        // Check if the child exists and belongs to us
        if PROCS[child_pid].parent != current {
            frame.a0 = usize::MAX;
            return;
        }

        // Already exited? Return immediately.
        if PROCS[child_pid].state == ProcessState::Free {
            frame.a0 = PROCS[child_pid].exit_code;
            return;
        }

        // Child still running — block
        PROCS[current].ipc_target = child_pid; // who we're waiting for
        PROCS[current].state = ProcessState::BlockedWait;

        schedule(frame, current);
    }
}

// ── Voluntary Yield ──────────────────────────────────────────

/// SYS_YIELD() — voluntarily give up the time slice.
///
/// Convention: no arguments. Returns: a0 = 0.
/// Marks the caller Ready and switches to the next process.
/// If no other process is Ready, returns immediately.
pub fn sys_yield(frame: &mut TrapFrame) {
    frame.sepc += 4;

    let current = unsafe { CURRENT_PID };
    if current == 0 { return; }

    unsafe {
        // Check if there's anyone else to switch to
        let mut found = false;
        for offset in 1..(MAX_PROCS - 1) {
            let i = ((current - 1 + offset) % (MAX_PROCS - 1)) + 1;
            if PROCS[i].state == ProcessState::Ready {
                found = true;
                break;
            }
        }
        if !found {
            frame.a0 = 0;
            return; // we're the only one — keep running
        }

        PROCS[current].state = ProcessState::Ready;
        schedule(frame, current);
    }

    frame.a0 = 0;
}

// ── Preemptive Scheduling ────────────────────────────────────

/// Timer-driven preemption — called from the timer interrupt handler.
///
/// If a user process is running, forcibly save its state and switch
/// to the next Ready process (round-robin). This is what prevents
/// a busy-loop process from starving everyone else.
pub fn preempt(frame: &mut TrapFrame) {
    unsafe {
        let current = CURRENT_PID;
        if current == 0 { return; } // no user process running

        // Find next Ready process (round-robin from current+1)
        let mut next = 0;
        for offset in 1..(MAX_PROCS - 1) {
            let i = ((current - 1 + offset) % (MAX_PROCS - 1)) + 1;
            if PROCS[i].state == ProcessState::Ready {
                next = i;
                break;
            }
        }

        if next == 0 {
            return; // no one else to run — let current continue
        }

        // Preempt: save current, load next
        PROCS[current].context = *frame;
        PROCS[current].state = ProcessState::Ready;

        *frame = PROCS[next].context;
        PROCS[next].state = ProcessState::Running;
        CURRENT_PID = next;

        let next_satp = PROCS[next].satp;
        asm!(
            "csrw satp, {0}",
            "sfence.vma zero, zero",
            in(reg) next_satp,
        );
    }
}

// ── Scheduler ──────────────────────────────────────────────────

/// Save current process and switch to the next ready process.
///
/// Called when a process blocks (SEND/RECEIVE/WAIT with no rendezvous).
/// Uses round-robin: scans from the blocked PID forward, wrapping around.
/// The frame on the kernel stack is overwritten with the next process's
/// saved context. When we return to trap.S, it restores and srets to
/// the next process.
unsafe fn schedule(frame: &mut TrapFrame, blocked_pid: usize) {
    // Save current process's registers
    PROCS[blocked_pid].context = *frame;

    // Find next ready process (round-robin from blocked_pid + 1)
    let mut next = 0;
    for offset in 1..MAX_PROCS {
        let i = ((blocked_pid - 1 + offset) % (MAX_PROCS - 1)) + 1;
        if PROCS[i].state == ProcessState::Ready {
            next = i;
            break;
        }
    }

    if next == 0 {
        // All processes blocked — deadlock
        panic!("Deadlock: no runnable processes (PID {} blocked)", blocked_pid);
    }

    // Load next process's context onto the kernel stack
    *frame = PROCS[next].context;
    PROCS[next].state = ProcessState::Running;
    CURRENT_PID = next;

    // Switch page table
    let next_satp = PROCS[next].satp;
    asm!(
        "csrw satp, {0}",
        "sfence.vma zero, zero",
        in(reg) next_satp,
    );
}
